//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.03 at 05:03:24 PM IST 
//


package org.muqtar.vo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.muqtar.vo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.muqtar.vo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Playmanifest }
     * 
     */
    public Playmanifest createPlaymanifest() {
        return new Playmanifest();
    }

    /**
     * Create an instance of {@link Playmanifest.Channels }
     * 
     */
    public Playmanifest.Channels createPlaymanifestChannels() {
        return new Playmanifest.Channels();
    }

    /**
     * Create an instance of {@link Playmanifest.Channels.Channel }
     * 
     */
    public Playmanifest.Channels.Channel createPlaymanifestChannelsChannel() {
        return new Playmanifest.Channels.Channel();
    }

}
